# Enhanced GitHub Pages workflow for Enterprise accounts
name: Deploy to GitHub Pages (Enterprise)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
  # Allows you to run this workflow manually
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Concurrent deployment handling
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job for Static HTML
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Create placeholder directories
        run: |
          mkdir -p images/logos images/fallbacks
      
      - name: Create placeholder SVG
        run: |
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="60" viewBox="0 0 100 60"><rect width="100" height="60" fill="#F0F0F0"/><text x="50" y="30" font-family="Arial, sans-serif" font-size="10" fill="#888888" text-anchor="middle" alignment-baseline="middle">Logo</text></svg>' > images/logos/placeholder.svg
      
      - name: Create placeholder image
        run: |
          echo '<!-- Car Placeholder -->' > images/fallbacks/car-placeholder.jpg
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
